#!/bin/bash 

yay -Syu --noconfirm fish vesktop hyprland hyprshot grim slurp hyprshot hyprpolkitagent spotify spicetify-cli betterbird keepassxc steam waybar fcitx5 nautilus hyprpaper ttf-jetbrains-mono-nerd && exec ./setup.sh || read -p "error occured! you might wanna check whats goin' on. continue anyway? (Y/N) " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]; then
   cd ~/
   sudo mkdir clones
   cd clones/
   sudo git clone https://github.com/ntrop6/dotfiles.git
   sudo 'cp' -rf ~/clones/dotfiles/*  ~/.config/ && echo "
should be done! (hopefully)"
fi
if [[ $REPLY =~ ^[Nn]$ ]]; then
   echo "
oke bye bye"
   exit
fi

