# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
# windowrule = opacity 0.89 override 0.89 override, match:class .*

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland 1

workspace = special:special, gapsout:12
windowrule = match:class spotify, workspace 4 silent
windowrule = match:class org.keepassxc.KeePassXC, workspace 7 silent
windowrule = match:class steam, workspace 5 silent
#windowrule = match:class vesktop, workspace 3 silent
#windowrule = match:class zen, workspace 2 silent
#windowrule = match:class com.mitchellh.ghostty, workspace 1 silent
